package:
  name: embedpy
  version: {{ environ.get('EMBEDPY_VERSION', 'noversion') }}

source:
  path: ..

build:
  detect_binary_files_with_prefix: False
  script_env:
    QLIC

requirements:
  build:
    - m2w64-make                     [win]
    - {{ compiler('c') }}
  host:
    - python
    - kdb
  run:
    - python
    - kdb
test:
  source_files:
    - test.q
    - tests/

about:
  home: https://github.com/KxSystems/embedPy
  summary: allows the kdb+ interpreter to manipulate Python objects
