package:
  name: embedpy
  version: {{ environ.get('EMBEDPY_VERSION', 'noversion') }}

source:
  path: ..

build:
  detect_binary_files_with_prefix: False
  script_env:
    QLIC
  overlinking_ignore_patterns:
   - "q/*/p.so"

requirements:
  build:
    - m2w64-make                   #  [win]
    - {{ compiler('c') }}          #  [not osx]
  host:
    - python
    - kdb
  run:
    - python
    - kdb
test:
  source_files:
    - test.q
    - tests/
    - conda-recipe/prep_requirements.q

about:
  home: https://github.com/KxSystems/embedPy
  summary: allows the kdb+ interpreter to manipulate Python objects
